### ISSUE TITLE
JUnit Youtube tutorial is outdated

### ISSUE THREAD

**Issue by thisHermit** [crio-do/CSoD-Introductory-Reading-Material#10]
> JUnit tutorial [Video] - https://www.youtube.com/watch?v=o5k9NOR9lrI

This link is outdated and does not use JUnit 5. Please replace this by a suitable tutorial.

**Comment by upa8** [comment]
Thank you @thisHermit .

Will do this asap.

**Comment by thisHermit** [comment]
Forgot to close the issue.
